<?php
/**
 * @file
 * unca_maps.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function unca_maps_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-map_item-body'
  $field_instances['node-map_item-body'] = array(
    'bundle' => 'map_item',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-map_item-field_image'
  $field_instances['node-map_item-field_image'] = array(
    'bundle' => 'map_item',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => 'medium',
        ),
        'type' => 'image',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_image',
    'label' => 'Image',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => 'map-item',
      'file_extensions' => 'png gif jpg jpeg',
      'focus' => 0,
      'focus_lock_ratio' => 0,
      'focus_min_size' => '',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '300x300',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'imagefield_crop',
      'settings' => array(
        'collapsible' => 2,
        'croparea' => '500x500',
        'enforce_minimum' => 1,
        'enforce_ratio' => 1,
        'preview_image_style' => 'medium',
        'progress_indicator' => 'throbber',
        'resolution' => '300x300',
      ),
      'type' => 'imagefield_crop_widget',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-map_item-field_link'
  $field_instances['node-map_item-field_link'] = array(
    'bundle' => 'map_item',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Link to more information about this place. Many of these will be off-site links.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'link',
        'settings' => array(),
        'type' => 'link_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_link',
    'label' => 'Link',
    'required' => 0,
    'settings' => array(
      'attributes' => array(
        'class' => '',
        'configurable_title' => 0,
        'rel' => '',
        'target' => 'default',
        'title' => '',
      ),
      'display' => array(
        'url_cutoff' => 80,
      ),
      'enable_tokens' => 1,
      'rel_remove' => 'default',
      'title' => 'required',
      'title_maxlength' => 255,
      'title_value' => '',
      'url' => 0,
      'user_register_form' => FALSE,
      'validate_url' => 1,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'link',
      'settings' => array(),
      'type' => 'link_field',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-map_item-field_location_type_term'
  $field_instances['node-map_item-field_location_type_term'] = array(
    'bundle' => 'map_item',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_location_type_term',
    'label' => 'Location Type',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-map_item-field_location_with_map'
  $field_instances['node-map_item-field_location_with_map'] = array(
    'bundle' => 'map_item',
    'default_value' => array(
      0 => array(
        'location_settings' => array(
          'display' => array(
            'hide' => array(
              'additional' => 'additional',
              'city' => 'city',
              'coords' => 'coords',
              'country' => 'country',
              'country_name' => 'country_name',
              'locpick' => 0,
              'map_link' => 'map_link',
              'name' => 'name',
              'postal_code' => 'postal_code',
              'province' => 'province',
              'province_name' => 'province_name',
              'street' => 'street',
            ),
          ),
          'form' => array(
            'fields' => array(
              'additional' => array(
                'collect' => 0,
                'default' => '',
                'weight' => 6,
              ),
              'city' => array(
                'collect' => 0,
                'default' => '',
                'weight' => 8,
              ),
              'country' => array(
                '#parents' => array(
                  0 => 'field_location_with_map',
                  1 => 'und',
                  2 => 0,
                ),
                'collect' => 4,
                'default' => 'us',
                'weight' => 14,
              ),
              'delete_location' => array(
                'default' => FALSE,
                'nodiff' => TRUE,
              ),
              'is_primary' => array(
                'default' => 0,
              ),
              'latitude' => array(
                'default' => 0,
              ),
              'lid' => array(
                'default' => FALSE,
              ),
              'locpick' => array(
                '#parents' => array(
                  0 => 'field_location_with_map',
                  1 => 'und',
                  2 => 0,
                ),
                'collect' => 1,
                'default' => FALSE,
                'nodiff' => TRUE,
                'weight' => 20,
              ),
              'longitude' => array(
                'default' => 0,
              ),
              'name' => array(
                'collect' => 0,
                'default' => '',
                'weight' => 2,
              ),
              'postal_code' => array(
                'collect' => 0,
                'default' => '',
                'weight' => 12,
              ),
              'province' => array(
                'collect' => 0,
                'default' => '',
                'weight' => 10,
                'widget' => 'autocomplete',
              ),
              'source' => array(
                'default' => 0,
              ),
              'street' => array(
                'collect' => 0,
                'default' => '',
                'weight' => 4,
              ),
            ),
          ),
        ),
        'country' => 'us',
        'locpick' => array(
          'user_latitude' => 35.6173955796,
          'user_longitude' => -82.5686073303,
        ),
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'location_cck',
        'settings' => array(),
        'type' => 'location_map',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_location_with_map',
    'label' => 'Location with Map',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'location_cck',
      'settings' => array(),
      'type' => 'location',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-map_item-field_map_number'
  $field_instances['node-map_item-field_map_number'] = array(
    'bundle' => 'map_item',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_map_number',
    'label' => 'Map Number',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Body');
  t('Image');
  t('Link');
  t('Link to more information about this place. Many of these will be off-site links.');
  t('Location Type');
  t('Location with Map');
  t('Map Number');

  return $field_instances;
}
